services:
  - type: web
    name: chess-with-ai
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production 