services:
  - type: web
    name: chess-with-ai
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production 